packageExtensions:
  "@nrwl/tao@*":
    dependencies:
      "@angular-devkit/architect": "*"
      "@angular-devkit/core": "*"
      "@angular-devkit/schematics": "*"
  "@nrwl/workspace@*":
    dependencies:
      "@angular-devkit/core": "*"
      "@angular-devkit/schematics": "*"
  snyk-docker-plugin@*:
    dependencies:
      minimatch: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-prune-prod.cjs
    spec: "https://raw.githubusercontent.com/troncali/yarn-prune-prod/main/bundles/%40yarnpkg/plugin-prune-prod.js"

yarnPath: .yarn/releases/yarn-3.0.0.cjs
