yarnPath: .yarn/releases/yarn-sources.cjs
# pnpMode: loose
# packageExtensions: {
# 	"@apollo/gateway@*": {
# 		dependencies: {
# 			"node-fetch": "*"
# 		}
# 	},
# 	"@mapbox/node-pre-gyp@*": {
# 		dependencies: {
# 			"aws-sdk": "*",
# 			"mock-aws-s3": "*",
# 			"nock": "*",
# 			"npm": "*"
# 		}
# 	},
# 	"@nestjs/common@*": {
# 		dependencies: {
# 			"cache-manager": "*"
# 		}
# 	},
# 	"@nestjs/core@*": {
# 		dependencies: {
# 			"@nestjs/microservices": "*",
# 			"@nestjs/platform-express": "*",
# 			"@nestjs/websockets": "*"
# 		}
# 	},
# 	"@nestjs/graphql@*": {
# 		dependencies: {
# 			"apollo-server-core": "*",
# 			"apollo-server-express": "*",
# 			"@apollo/federation": "*"
# 		}
# 	},
# 	"@nestjs/microservices@*": {
# 		dependencies: {
# 			"amqp-connection-manager": "*",
# 			"amqplib": "*",
# 			"grpc": "*",
# 			"kafkajs": "*",
# 			"mqtt": "*",
# 			"nats": "*",
# 			"redis": "*"
# 		}
# 	},
# 	"@npmcli-arborist@*": {
# 		dependencies: {
# 			"mkdirp": "*",
# 			"ssri": "*"
# 		}
# 	},
# 	"@ts-morph/common@*": {
# 		dependencies: {
# 			"source-map-support": "*"
# 		}
# 	},
# 	"bytebuffer@*": {
# 		dependencies: {
# 			"memcpy": "*"
# 		}
# 	},
# 	"debug@*": {
# 		dependencies: {
# 			"supports-color": "*"
# 		}
# 	},
# 	"fast-json-stringify@*": {
# 		dependencies: {
# 			"long": "*"
# 		}
# 	},
# 	"follow-redirects@*": {
# 		dependencies: {
# 			"debug": "*"
# 		}
# 	},
# 	"hdb-pool@*": {
# 		dependencies: {
# 			"@sap/hana-client": "*",
# 			"hdb": "*"
# 		}
# 	},
# 	"pg@*": {
# 		dependencies: {
# 			"pg-native": "*"
# 		}
# 	},
# 	"mongodb@*": {
# 		dependencies: {
# 			"aws4": "*",
# 			"mongodb-client-encryption": "*"
# 		}
# 	},
# 	"mysql@*": {
# 		dependencies: {
# 			"cardinal": "*",
# 		}
# 	},
# 	"mysql2@*": {
# 		dependencies: {
# 			"cardinal": "*"
# 		}
# 	},
# 	"node-pre-gyp@*": {
# 		dependencies: {
# 			"aws-sdk": "*",
# 			"npm": "*",
# 			"request": "*"
# 		}
# 	},
# 	"pino@*": {
# 		dependencies: {
# 			"pino-pretty": "*"
# 		}
# 	},
# 	"promise-inflight@*": {
# 		dependencies: {
# 			"bluebird": "*"
# 		}
# 	},
# 	"react-native-sqlite-storage@*": {
# 		dependencies: {
# 			"react-native": "*"
# 		}
# 	},
# 	"typeorm@*": {
# 		dependencies: {
# 			"@sap/hana-client": "*",
# 			"better-sqlite3": "*",
# 			"hdb-pool": "*",
# 			"ioredis": "*",
# 			"mongodb": "*",
# 			"mssql": "*",
# 			"mysql": "*",
# 			"mysql2": "*",
# 			"oracledb": "*",
# 			"pg-native": "*",
# 			"pg-query-stream": "*",
# 			"react-native-sqlite-storage": "*",
# 			"redis": "*",
# 			"sql.js": "*",
# 			"sqlite3": "*",
# 			"typeorm-aurora-data-api-driver": "*"
# 		}
# 	},
# 	"typeorm-aurora-data-api-driver@*": {
# 		dependencies: {
# 			"aws-sdk": "*"
# 		}
# 	},
# 	"typescript@*": {
# 		dependencies: {
# 			"source-map-support": "*"
# 		}
# 	},
# 	"ws@*": {
# 		dependencies: {
# 			"bufferutil": "*",
# 			"utf-8-validate": "*"
# 		}
# 	}
# }
