yarnPath: .yarn/releases/yarn-sources.cjs
packageExtensions: {
	"@nrwl/tao@*": {
		dependencies: {
			"@angular-devkit/core": "*",
			"@angular-devkit/schematics": "*",
			"@angular-devkit/architect": "*"
		}
	},
	"@nrwl/workspace@*": {
		dependencies: {
			"@angular-devkit/core": "*",
			"@angular-devkit/schematics": "*"
		}
	},
	"snyk-docker-plugin@*": {
		dependencies: {
			"minimatch": "*"
		}
	}
}
