enableGlobalCache: false

packageExtensions:
  "@compodoc/compodoc@*":
    dependencies:
      "@babel/plugin-proposal-private-methods": "*"
  "@nestjs/mercurius@*":
    dependencies:
      lodash: "*"
  "@nrwl/nest@*":
    dependencies:
      semver: "*"
  "@nrwl/tao@*":
    dependencies:
      "@angular-devkit/architect": "*"
      "@angular-devkit/core": "*"
      "@angular-devkit/schematics": "*"
  "@nrwl/workspace@*":
    dependencies:
      "@angular-devkit/core": "*"
      "@angular-devkit/schematics": "*"
  "@nx-plus/vue@*":
    dependencies:
      "@nrwl/devkit": "*"
  "@vue/cli-service@*":
    dependencies:
      "@vue/compiler-sfc": "*"
  nx@*:
    dependencies:
      "@angular-devkit/architect": "*"
      "@angular-devkit/core": "*"
  snyk-docker-plugin@*:
    dependencies:
      minimatch: "*"
  snyk@*:
    dependencies:
      lodash: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-prune-prod.cjs
    spec: "https://raw.githubusercontent.com/troncali/yarn-prune-prod/main/bundles/%40yarnpkg/plugin-prune-prod.js"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-4.0.0-rc.13.git.20220720.hash-02a48ec.cjs
