packageExtensions:
  "@nrwl/tao@*":
    dependencies:
      "@angular-devkit/architect": "*"
      "@angular-devkit/core": "*"
      "@angular-devkit/schematics": "*"
  "@nrwl/workspace@*":
    dependencies:
      "@angular-devkit/core": "*"
      "@angular-devkit/schematics": "*"
  "@nx-plus/vue@*":
    dependencies:
      "@nrwl/devkit": "*"
  snyk-docker-plugin@*:
    dependencies:
      minimatch: "*"
  snyk@*:
    dependencies:
      lodash: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-prune-prod.cjs
    spec: "https://raw.githubusercontent.com/troncali/yarn-prune-prod/main/bundles/%40yarnpkg/plugin-prune-prod.js"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
