version: "3"

services:
    db:
        ports:
            - ${DB_PORT}:${DB_PORT}
        # command: ["postgres", "-d", "2"]
        command: [
                "postgres",
                # Set runtime parameters
                "-c",
                "log_statement=all" # Which SQL statements to log
            ]

    nginx:
        volumes:
            - ./src/nginx/dev-certs:/etc/letsencrypt/live/localhost
            - ./builds/frontend:/etc/nginx/html
        environment:
            - APP_DOMAIN=localhost
            - BACKEND_SERVICE_NAME=host.docker.internal # localhost on host matchine
