version: "3.8"

services:
    backend:
        depends_on:
            - db

    nginx:
        depends_on:
            - backend
            - placeholder
            - db
        volumes:
            - certbot-etc:/etc/letsencrypt:ro
        # USE 1. ports if mapping the nginx service directly to host ports
        ports:
            - "80:80"
            - "443:443"
        # OR 2. settings below if using a proxy in front of the nginx service
        # networks:
        #     - proxy-network
        # environment:
        #     - VIRTUAL_HOST=${APP_DOMAIN},www.${APP_DOMAIN},${STAGING_DOMAIN}
        #     - VIRTUAL_PROTO=https
        #     - VIRTUAL_PORT=443
        # expose:
        #     - 80
        #     - 443

    certbot:
        depends_on:
            - nginx

    worker:
        depends_on:
            - nginx
            - certbot

secrets:
    DB_USERNAME:
        file: /srv/nest-vue/secrets/DB_USERNAME
    DB_PASSWORD:
        file: /srv/nest-vue/secrets/DB_PASSWORD
    BACKEND_SESSION_KEY_1:
        file: /srv/nest-vue/secrets/BACKEND_SESSION_KEY_1
    NGINX_STAGING_AUTH:
        file: /srv/nest-vue/secrets/NGINX_STAGING_AUTH
# networks:
#     proxy-network:
#         name: proxy-network
#         external: true
